export const AK_PLAYERS = {
  '1630595': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
  '1630596': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
  '1630591': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
  '1630215': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
  '1630552': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
};

export const WL_PLAYERS = {
  '1630567': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
  '1630563': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
  '1630537': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
  '1630578': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
  '1630550': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
};

export const EC_PLAYERS = {
  '1630224': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
  '1630547': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
  '1630558': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
  '1630539': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
  '1630536': {
    points: 0,
    threePointersMade: 0,
    rebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    turnovers: 0,
  },
};
